// source: location.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf')
var goog = jspb
var global = Function('return this')()

goog.exportSymbol('proto.Empty', null, global)
goog.exportSymbol('proto.LocationUpdate', null, global)
goog.exportSymbol('proto.LocationUpdateResponse', null, global)
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Empty = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.Empty, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Empty.displayName = 'proto.Empty'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LocationUpdateResponse = function (opt_data) {
  jspb.Message.initialize(
    this,
    opt_data,
    0,
    -1,
    proto.LocationUpdateResponse.repeatedFields_,
    null
  )
}
goog.inherits(proto.LocationUpdateResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LocationUpdateResponse.displayName = 'proto.LocationUpdateResponse'
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LocationUpdate = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.LocationUpdate, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LocationUpdate.displayName = 'proto.LocationUpdate'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.Empty.prototype.toObject = function (opt_includeInstance) {
    return proto.Empty.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.Empty} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.Empty.toObject = function (includeInstance, msg) {
    var f,
      obj = {}

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Empty}
 */
proto.Empty.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.Empty()
  return proto.Empty.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Empty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Empty}
 */
proto.Empty.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Empty.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.Empty.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Empty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Empty.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.LocationUpdateResponse.repeatedFields_ = [1]

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.LocationUpdateResponse.prototype.toObject = function (
    opt_includeInstance
  ) {
    return proto.LocationUpdateResponse.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.LocationUpdateResponse} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.LocationUpdateResponse.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        locationupdatesList: jspb.Message.toObjectList(
          msg.getLocationupdatesList(),
          proto.LocationUpdate.toObject,
          includeInstance
        ),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LocationUpdateResponse}
 */
proto.LocationUpdateResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.LocationUpdateResponse()
  return proto.LocationUpdateResponse.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LocationUpdateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LocationUpdateResponse}
 */
proto.LocationUpdateResponse.deserializeBinaryFromReader = function (
  msg,
  reader
) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = new proto.LocationUpdate()
        reader.readMessage(
          value,
          proto.LocationUpdate.deserializeBinaryFromReader
        )
        msg.addLocationupdates(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LocationUpdateResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.LocationUpdateResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LocationUpdateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LocationUpdateResponse.serializeBinaryToWriter = function (
  message,
  writer
) {
  var f = undefined
  f = message.getLocationupdatesList()
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.LocationUpdate.serializeBinaryToWriter
    )
  }
}

/**
 * repeated LocationUpdate locationUpdates = 1;
 * @return {!Array<!proto.LocationUpdate>}
 */
proto.LocationUpdateResponse.prototype.getLocationupdatesList = function () {
  return /** @type{!Array<!proto.LocationUpdate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.LocationUpdate, 1)
  )
}

/**
 * @param {!Array<!proto.LocationUpdate>} value
 * @return {!proto.LocationUpdateResponse} returns this
 */
proto.LocationUpdateResponse.prototype.setLocationupdatesList = function (
  value
) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value)
}

/**
 * @param {!proto.LocationUpdate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.LocationUpdate}
 */
proto.LocationUpdateResponse.prototype.addLocationupdates = function (
  opt_value,
  opt_index
) {
  return jspb.Message.addToRepeatedWrapperField(
    this,
    1,
    opt_value,
    proto.LocationUpdate,
    opt_index
  )
}

/**
 * Clears the list making it empty but non-null.
 * @return {!proto.LocationUpdateResponse} returns this
 */
proto.LocationUpdateResponse.prototype.clearLocationupdatesList = function () {
  return this.setLocationupdatesList([])
}

if (jspb.Message.GENERATE_TO_OBJECT) {
  /**
   * Creates an object representation of this proto.
   * Field names that are reserved in JavaScript and will be renamed to pb_name.
   * Optional fields that are not set will be set to undefined.
   * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
   * For the list of reserved names please see:
   *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
   * @param {boolean=} opt_includeInstance Deprecated. whether to include the
   *     JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @return {!Object}
   */
  proto.LocationUpdate.prototype.toObject = function (opt_includeInstance) {
    return proto.LocationUpdate.toObject(opt_includeInstance, this)
  }

  /**
   * Static version of the {@see toObject} method.
   * @param {boolean|undefined} includeInstance Deprecated. Whether to include
   *     the JSPB instance for transitional soy proto support:
   *     http://goto/soy-param-migration
   * @param {!proto.LocationUpdate} msg The msg instance to transform.
   * @return {!Object}
   * @suppress {unusedLocalVariables} f is only used for nested messages
   */
  proto.LocationUpdate.toObject = function (includeInstance, msg) {
    var f,
      obj = {
        characterid: jspb.Message.getFieldWithDefault(msg, 1, ''),
        online: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
        x: jspb.Message.getFieldWithDefault(msg, 3, 0),
        y: jspb.Message.getFieldWithDefault(msg, 4, 0),
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LocationUpdate}
 */
proto.LocationUpdate.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.LocationUpdate()
  return proto.LocationUpdate.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LocationUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LocationUpdate}
 */
proto.LocationUpdate.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setCharacterid(value)
        break
      case 2:
        var value = /** @type {boolean} */ (reader.readBool())
        msg.setOnline(value)
        break
      case 3:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setX(value)
        break
      case 4:
        var value = /** @type {number} */ (reader.readInt32())
        msg.setY(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LocationUpdate.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.LocationUpdate.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LocationUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LocationUpdate.serializeBinaryToWriter = function (message, writer) {
  var f = undefined
  f = message.getCharacterid()
  if (f.length > 0) {
    writer.writeString(1, f)
  }
  f = message.getOnline()
  if (f) {
    writer.writeBool(2, f)
  }
  f = message.getX()
  if (f !== 0) {
    writer.writeInt32(3, f)
  }
  f = message.getY()
  if (f !== 0) {
    writer.writeInt32(4, f)
  }
}

/**
 * optional string characterId = 1;
 * @return {string}
 */
proto.LocationUpdate.prototype.getCharacterid = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/**
 * @param {string} value
 * @return {!proto.LocationUpdate} returns this
 */
proto.LocationUpdate.prototype.setCharacterid = function (value) {
  return jspb.Message.setProto3StringField(this, 1, value)
}

/**
 * optional bool online = 2;
 * @return {boolean}
 */
proto.LocationUpdate.prototype.getOnline = function () {
  return /** @type {boolean} */ (
    jspb.Message.getBooleanFieldWithDefault(this, 2, false)
  )
}

/**
 * @param {boolean} value
 * @return {!proto.LocationUpdate} returns this
 */
proto.LocationUpdate.prototype.setOnline = function (value) {
  return jspb.Message.setProto3BooleanField(this, 2, value)
}

/**
 * optional int32 x = 3;
 * @return {number}
 */
proto.LocationUpdate.prototype.getX = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0))
}

/**
 * @param {number} value
 * @return {!proto.LocationUpdate} returns this
 */
proto.LocationUpdate.prototype.setX = function (value) {
  return jspb.Message.setProto3IntField(this, 3, value)
}

/**
 * optional int32 y = 4;
 * @return {number}
 */
proto.LocationUpdate.prototype.getY = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0))
}

/**
 * @param {number} value
 * @return {!proto.LocationUpdate} returns this
 */
proto.LocationUpdate.prototype.setY = function (value) {
  return jspb.Message.setProto3IntField(this, 4, value)
}

goog.object.extend(exports, proto)
